version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_APP_DB: ${POSTGRES_APP_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d/schema
      - ./database/scripts/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DEFAULT_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  back:
    image: timesphere-backend:latest
    environment:
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_APP_DB: ${POSTGRES_APP_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${BACK_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
  front:
    image: timesphere-frontend:latest
    environment:
      BACKEND_URL: http://back:${BACK_PORT}
    ports:
      - "${FRONT_PORT}:3000"
    depends_on:
      - back
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - back
      - front
volumes:
  postgres-data:
