domains:
  - domain: timesphere.systems
    type: PRIMARY
ingress:
  rules:
    - component:
        name: timesphere-react
      match:
        path:
          prefix: /
    - component:
        name: timesphere-fastapi
      match:
        path:
          prefix: /api/
name: timesphere
region: lon
databases:
  - cluster_name: db-postgresql-timesphere
    db_name: timesphere
    db_user: timesphere
    engine: PG
    name: db-postgresql-timesphere
    production: true
    version: "16"
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: timesphere-systems/timesphere
    envs:
      BACKEND_URL: "https://timesphere.systems/api"
      REACT_APP_AUTHZERO_DOMAIN: "dev-ix6nt3x32jxvquyz.us.auth0.com"
      REACT_APP_AUTHZERO_CLIENT_ID: "PIg9pxjlhr8Fg8FUhjjdq2mfjMbIzEWJ"
      REACT_APP_AUTHZERO_AUDIENCE: "https://timesphere.systems/api"
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: timesphere-react
    source_dir: /front
  - build_command: python -m pip install -r requirements.txt
    github:
      branch: main
      deploy_on_push: true
      repo: timesphere-systems/timesphere
    envs:
      - key: POSTGRES_DB_NAME
        value: timesphere
      - key: POSTGRES_APP_USER
        value: ${db-postgresql-oxinar-london.USERNAME}
      - key: POSTGRES_APP_PASSWORD
        value: ${db-postgresql-oxinar-london.PASSWORD}
      - key: POSTGRES_HOST
        value: ${db-postgresql-oxinar-london.HOSTNAME}
      - key: POSTGRES_PORT
        value: ${db-postgresql-oxinar-london.PORT}
      - key: AUTHZERO_DOMAIN
        value: "dev-ix6nt3x32jxvquyz.us.auth0.com"
      - key: AUTHZERO_AUDIENCE
        value: "https://timesphere.systems/api"
    environment_slug: python
    name: timesphere-fastapi
    source_dir: /back
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: uvicorn api.main:app --host 0.0.0.0 --port 5000
